# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: iuid 0.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "iuid"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["mh"]
  s.date = "2016-05-27"
  s.description = "Iuid generates and keeps uids stored. It generates the next unique uid based on a category range"
  s.email = "mh+iuid@immerda.ch"
  s.executables = ["iuid"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/iuid",
    "iuid.gemspec",
    "lib/VERSION",
    "lib/iuid.rb",
    "lib/iuid/default_config.yaml",
    "lib/iuid/version.rb",
    "spec/data/.keep",
    "spec/iuid_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://www.immerda.ch"
  s.licenses = ["GPLv3"]
  s.rubygems_version = "2.3.0"
  s.summary = "Iuid a simple uid generator and storage"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<moneta>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-pending_for>, [">= 0"])
    else
      s.add_dependency(%q<moneta>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-pending_for>, [">= 0"])
    end
  else
    s.add_dependency(%q<moneta>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-pending_for>, [">= 0"])
  end
end

